### ISSUE TITLE
Is your bookmark manager thread safe?

### ISSUE THREAD

**Issue by depth42** [regexident/Sandbox#1]
I am no Swift expert, but your bookmark manager mutates a dictionary which gets stored in NSUserDefaults. I think, as you use NSUserDefaults, that this is an NSMutableDictionary which does not have value semantics and therefore is not thread safe.
You should either protect the resource or add a main-thread-only disclaimer.

**Comment by regexident** [comment]
The method returns a Swift `Dictionary`, which has value semantics in Swift, so it should be safe.
