### ISSUE TITLE
Code update

### ISSUE THREAD

**Issue by rmvz3** [regexident/Sandbox#2]
Hi. I love this library but it isn't usable at the moment. It seems that Swift has changed a lot since it was written and it simply doesn't compile now.

Any chance on updating the code?

Thank you

**Comment by regexident** [comment]
I have pushed an updated version ([1.1.0](https://github.com/regexident/Sandbox/releases/tag/1.1.0)).

**Comment by rmvz3** [comment]
Thank you very much! :)
